//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NET_Project_Client
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameOrder
    {
        public int Gid { get; set; }
        public int MoveID { get; set; }
        public int TheMove { get; set; }
    }
}
